## Importing Libraries

In [2]:
import yfinance as yf

# For visualization
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('seaborn-v0_8-darkgrid')

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

## Download Minute Data

In [3]:
# Download the minute data for Apple
apple_minute_data = yf.download(tickers='AAPL', period='5d', interval='1m', auto_adjust=True, multi_level_index=False)
apple_minute_data.head()

[*********************100%***********************]  1 of 1 completed

,Close,High,Low,Open,Volume
Datetime,,,,,
2026-08-06 09:30:00-04:00,314.679993,316.130005,314.209991,314.339996,1639773
2026-08-06 09:31:00-04:00,315.730011,315.750000,314.019989,314.679993,206049
2026-08-06 09:32:00-04:00,315.216797,315.850006,314.820007,315.739990,252619
2026-08-06 09:33:00-04:00,314.690002,315.774994,314.570007,315.184998,262739
2026-08-06 09:34:00-04:00,314.429993,314.720001,313.730103,314.557007,298815

## Resample Data

In [11]:
# Aggregate function
ohlcv_dict = {'Open':'first',
             'High':'max',
             'Low':'min',
             'Close':'last',
             'Volume':'sum'}

In [12]:
# Resample data to 15 minutes data
apple_minute_data_15M = apple_minute_data.resample('15min').agg(ohlcv_dict)

# Drop the missing values
apple_minute_data_15M.dropna(inplace=True)

apple_minute_data_15M.head()

,Open,High,Low,Close,Volume
Datetime,,,,,
2026-08-06 09:30:00-04:00,314.339996,316.130005,313.489990,314.769989,4147313
2026-08-06 09:45:00-04:00,314.700104,316.289398,314.559998,314.769989,2397660
2026-08-06 10:00:00-04:00,314.799988,315.190002,312.700012,313.317810,1806031
2026-08-06 10:15:00-04:00,313.320007,313.454987,312.119995,312.839996,2135973
2026-08-06 10:30:00-04:00,312.799988,313.290009,311.780090,312.424988,1482040

In [14]:
# Resample data to 1 hour data
apple_minute_data_1H = apple_minute_data.resample('1h').agg(ohlcv_dict)
apple_minute_data_1H.dropna(inplace=True)
apple_minute_data_1H.head()

,Open,High,Low,Close,Volume
Datetime,,,,,
2026-08-06 09:00:00-04:00,314.339996,316.289398,313.489990,314.769989,6544973
2026-08-06 10:00:00-04:00,314.799988,315.190002,311.780090,313.343597,6773325
2026-08-06 11:00:00-04:00,313.359985,313.369904,309.230011,309.540009,4947854
2026-08-06 12:00:00-04:00,309.529999,311.760010,309.250000,311.660004,3026058
2026-08-06 13:00:00-04:00,311.649994,312.179993,310.709991,312.160004,3587882

In [16]:
# Resample data to 4 hours data
apple_minute_data_4H = apple_minute_data_4H = apple_minute_data.resample('4h').agg(ohlcv_dict)
apple_minute_data_4H.dropna(inplace=True)
apple_minute_data_4H.head()

,Open,High,Low,Close,Volume
Datetime,,,,,
2026-08-06 08:00:00-04:00,314.339996,316.289398,309.230011,309.540009,18266152
2026-08-06 12:00:00-04:00,309.529999,312.940002,309.250000,312.450012,14756831
2026-08-07 08:00:00-04:00,311.320007,314.809998,310.739990,312.149994,13244341
2026-08-07 12:00:00-04:00,312.140015,314.179993,311.540009,313.299988,12798332
2026-08-10 08:00:00-04:00,306.829987,307.455902,304.630005,307.179993,19249777